<a href="https://colab.research.google.com/github/joycedenny/introduction-to-python/blob/main/introduction_to_python_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales (3).csv to Supermarket_sales (3).csv


In [4]:
import pandas as pd
dataframe=pd.read_csv("Supermarket_sales (3).csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [5]:

print(dataframe.head(10))

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       

In [6]:
print(dataframe.tail(8))

       No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6

In [7]:
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [9]:
dataframe[["City"]]

City
0       Yangon
1    Naypyitaw
2       Yangon
3       Yangon
4       Yangon
..         ...
995  Naypyitaw
996   Mandalay
997     Yangon
998     Yangon
999     Yangon

[1000 rows x 1 columns]

In [10]:
dataframe[["City","Branch"]]

City Branch
0       Yangon      A
1    Naypyitaw      C
2       Yangon      A
3       Yangon      A
4       Yangon      A
..         ...    ...
995  Naypyitaw      C
996   Mandalay      B
997     Yangon      A
998     Yangon      A
999     Yangon      A

[1000 rows x 2 columns]

In [11]:
print(dataframe.index)

RangeIndex(start=0, stop=1000, step=1)


In [12]:
dataframe=dataframe.drop(["Tax"],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [14]:
dataframe=dataframe.drop(["gross_margin_percentage"],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_iincome  Rating  
0      Ewallet  522.83        26.1415     9.1  
1         Cash   76.40         3.8200     9.6  
2  Credit card  324.31        16.2155     7.4  
3      Ewallet  465.76        23.2880     8.4

In [18]:
max_price=dataframe.Unitprice.idxmax()
print(max_price)

122


In [19]:
max_price=dataframe.Unitprice.max()
print(max_price)

99.96


In [20]:
min_price=dataframe.Unitprice.min()
print(min_price)

10.08


In [21]:
min_price=dataframe.Unitprice.idxmin()
print(min_price)

944


In [23]:
dataframe.loc[dataframe["Customertype"]=="Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
5      6  699-14-3026      C  Naypyitaw       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Total       Date   Time  \
1    Electronic accessories      15.28         5    80.2200   3/8/2019  10:29   
2        Home and lifestyle      46.33         7   340.5255   3/3/2019  13:23   
4         Sports and travel      86.31         7   634.3785   2/8/2019  10:37   
5    Electronic accessories      85.39         7   627.6165  3/25/2019  18:30   
7        Home and lifestyle      73.56        10   772.3800  2/24/2019  11:38   
..                      ...        ...       ...        ...        ...    ...   
992  Electronic accessories      58.03         2   121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49        10   183.6450  2/22/2019  18:35   
995       Health and beauty      40.35         1    42.3675  1/29/2019  13:46   
996      Home and lifestyle      97.38        10  1022.4900   3/2/2019  17:16   
998      Home and lifestyle      65.82         1    69.1110  2/22/2019  15:33   

         Payment    cogs  gross_iincome  Rating  
1           Cash   76.40         3.8200     9.6  
2    Credit card  324.31        16.2155     7.4  
4        Ewallet  604.17        30.2085     5.3  
5        Ewallet  597.73        29.8865     4.1  
7        Ewallet  735.60        36.7800     8.0  
..           ...     ...            ...     ...  
992      Ewallet  116.06         5.8030     8.8  
993      Ewallet  174.90         8.7450     6.6  
995      Ewallet   40.35         2.0175     6.2  
996      Ewallet  973.80        48.6900     4.4  
998         Cash   65.82         3.2910     4.1  

[499 rows x 16 columns]

In [24]:
dataframe.loc[dataframe["Gender"]=="Female"]

No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
6       7  355-53-5943      A     Yangon       Member  Female   
7       8  315-22-5665      C  Naypyitaw       Normal  Female   
8       9  665-32-9167      A     Yangon       Member  Female   
..    ...          ...    ...        ...          ...     ...   
990   991  886-18-2897      A     Yangon       Normal  Female   
991   992  602-16-6955      B   Mandalay       Normal  Female   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
996   997  303-96-2227      B   Mandalay       Normal  Female   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Total       Date   Time  \
0         Health and beauty      74.69         7   548.9715   1/5/2019  13:08   
1    Electronic accessories      15.28         5    80.2200   3/8/2019  10:29   
6    Electronic accessories      68.84         6   433.6920  2/25/2019  14:36   
7        Home and lifestyle      73.56        10   772.3800  2/24/2019  11:38   
8         Health and beauty      36.26         2    76.1460  1/10/2019  17:15   
..                      ...        ...       ...        ...        ...    ...   
990      Food and beverages      56.56         5   296.9400  3/22/2019  19:06   
991       Sports and travel      76.60        10   804.3000  1/24/2019  18:10   
994  Electronic accessories      60.95         1    63.9975  2/18/2019  11:40   
996      Home and lifestyle      97.38        10  1022.4900   3/2/2019  17:16   
999     Fashion accessories      88.34         7   649.2990  2/18/2019  13:28   

         Payment    cogs  gross_iincome  Rating  
0        Ewallet  522.83        26.1415     9.1  
1           Cash   76.40         3.8200     9.6  
6        Ewallet  413.04        20.6520     5.8  
7        Ewallet  735.60        36.7800     8.0  
8    Credit card   72.52         3.6260     7.2  
..           ...     ...            ...     ...  
990  Credit card  282.80        14.1400     4.5  
991      Ewallet  766.00        38.3000     6.0  
994      Ewallet   60.95         3.0475     5.9  
996      Ewallet  973.80        48.6900     4.4  
999         Cash  618.38        30.9190     6.6  

[501 rows x 16 columns]

In [25]:
import numpy as np


In [26]:
student_marks_BA=[12,14,18]
marksarray=np.array(student_marks_BA)
print(marksarray)

[12 14 18]


In [28]:
student_marks_BA=[12,14,18],[15,19,20],[11,15,19]
marksarray=np.array(student_marks_BA)
print(marksarray)

[[12 14 18]
 [15 19 20]
 [11 15 19]]


In [29]:
student_marks_BA=[12,14],[15,19],[11,15],[14,12]
marksarray=np.array(student_marks_BA)
print(marksarray)

[[12 14]
 [15 19]
 [11 15]
 [14 12]]


In [31]:
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
values=np.arange(1,11)
print(values)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
values2=np.arange(5,11)
print(values2)

[ 5  6  7  8  9 10]


In [34]:
values3=np.arange(1,11,2)
print(values3)

[1 3 5 7 9]


In [35]:
values4=np.arange(50,60)
print(values4)

[50 51 52 53 54 55 56 57 58 59]


In [36]:
values5=np.arange(70,100,3)
print(values5)

[70 73 76 79 82 85 88 91 94 97]


In [41]:
zeroarray= np.zeros((1,8))
print(zeroarray)

[[0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
zeroarray= np.zeros((4,2))
print(zeroarray)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [43]:
zeroarray= np.zeros((1,6))
print(zeroarray)

[[0. 0. 0. 0. 0. 0.]]


In [44]:
onesarray= np.ones((8,2))
print(onesarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [45]:
from numpy.core.numeric import identity
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
from numpy.core.numeric import identity
identityarray=np.eye(5,2)
print(identityarray)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [49]:
len(zeroarray)

1

In [50]:
len(onesarray)

8

In [52]:
onesarray1= np.ones((4,3))
print(onesarray1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
print(onesarray1.shape)

(4, 3)


In [56]:
print(onesarray1.reshape(3,4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [57]:
print(onesarray1.reshape(6,2))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [58]:
values=np.random.randint(1,3,5)
print(values)

[1 1 2 1 1]


In [59]:
values=np.random.randint(1,20,8)
print(values)

[15  4 17 18 16  5 14  7]


In [60]:
values=np.random.randint(44,88,6)
print(values)

[44 55 55 54 47 74]


In [62]:
values=np.random.randint(25,50,(4,3))
print(values)

[[33 45 46]
 [45 27 38]
 [26 30 44]
 [28 29 25]]
